// ══════════════════════════════════════════════════════════════════
// SCIENCESPARK V2 — AQA TRIPLE SCIENCE ONLY CARDS
// ══════════════════════════════════════════════════════════════════
//
// 168 cards total: Biology 78 | Chemistry 47 | Physics 43
//
// TIER SYSTEM:
//   'triple_F' = Foundation + Higher Triple Science students
//   'triple_H' = Higher Triple Science students only
//
// FILTERING LOGIC:
//   Combined Foundation  → show tier: 'F'
//   Combined Higher      → show tier: 'F' or 'H'
//   Triple Foundation    → show tier: 'F', 'H', 'triple_F'
//   Triple Higher        → show ALL cards
//
// Each card: { id, tier, q, a, examQ: { q, marks, ms } }
// ══════════════════════════════════════════════════════════════════

// AQA Triple Biology Only Cards — B8-B15
// tier: 'triple_F' = Foundation + Higher Triple only
// tier: 'triple_H' = Higher Triple only

const TRIPLE_BIOLOGY = {

  b8: {
    name: "Photosynthesis (Triple)",
    cards: [
      { id:"b8-001", tier:"triple_F", q:"What are the two stages of photosynthesis?", a:"The light-dependent reaction (in the thylakoid membranes) and the light-independent reaction / Calvin cycle (in the stroma)", examQ:{q:"Describe where in the chloroplast each stage of photosynthesis takes place. [2 marks]", marks:2, ms:"Light-dependent reaction in thylakoid membranes (1); light-independent reaction/Calvin cycle in the stroma (1)"}},
      { id:"b8-002", tier:"triple_F", q:"What happens in the light-dependent reaction?", a:"Light energy splits water (photolysis), releasing oxygen, hydrogen and ATP", examQ:{q:"Explain what happens during the light-dependent reaction of photosynthesis. [3 marks]", marks:3, ms:"Light energy absorbed by chlorophyll (1); water is split by photolysis (1); oxygen released as a by-product, ATP and reduced NADP produced (1)"}},
      { id:"b8-003", tier:"triple_F", q:"What is photolysis?", a:"The splitting of water molecules using light energy, producing oxygen, hydrogen ions and electrons", examQ:{q:"Write the equation for photolysis of water. [2 marks]", marks:2, ms:"Water → oxygen + hydrogen (ions/electrons) (1); requires light energy (1)"}},
      { id:"b8-004", tier:"triple_F", q:"What happens in the Calvin cycle (light-independent reaction)?", a:"CO₂ is fixed using ATP and reduced NADP from the light-dependent reaction to produce glucose", examQ:{q:"Explain how the Calvin cycle uses products from the light-dependent reaction. [3 marks]", marks:3, ms:"ATP provides energy (1); reduced NADP provides hydrogen (1); used to fix CO₂ into glucose/G3P (1)"}},
      { id:"b8-005", tier:"triple_F", q:"What is the role of RuBisCO in the Calvin cycle?", a:"It is the enzyme that catalyses the fixation of CO₂ to RuBP (ribulose bisphosphate)", examQ:{q:"Describe the role of RuBisCO in photosynthesis. [2 marks]", marks:2, ms:"Enzyme (1); catalyses fixation/combination of CO₂ with RuBP (1)"}},
      { id:"b8-006", tier:"triple_H", q:"What is GP (glycerate-3-phosphate) and how is it produced?", a:"GP is a 3-carbon compound produced when CO₂ combines with RuBP in the Calvin cycle", examQ:{q:"Explain how GP is produced in the Calvin cycle. [2 marks]", marks:2, ms:"CO₂ combines with RuBP (1); catalysed by RuBisCO to form GP (1)"}},
      { id:"b8-007", tier:"triple_H", q:"What is GALP and how is it used?", a:"GALP (glyceraldehyde-3-phosphate) is produced from GP; it is used to make glucose and to regenerate RuBP", examQ:{q:"State two uses of GALP produced in the Calvin cycle. [2 marks]", marks:2, ms:"Used to synthesise glucose/sucrose/starch (1); used to regenerate RuBP (1)"}},
      { id:"b8-008", tier:"triple_F", q:"How does increasing light intensity affect the rate of the light-dependent reaction?", a:"More light energy is available so more ATP and reduced NADP are produced, increasing the rate until another factor becomes limiting", examQ:{q:"Explain why increasing light intensity increases the rate of photosynthesis up to a point. [3 marks]", marks:3, ms:"More light energy absorbed (1); more ATP/reduced NADP produced (1); rate plateaus when another factor becomes limiting e.g. CO₂ concentration (1)"}},
      { id:"b8-009", tier:"triple_F", q:"How does CO₂ concentration affect the Calvin cycle?", a:"Higher CO₂ concentration increases the rate of the Calvin cycle as more substrate is available for RuBisCO", examQ:{q:"Explain the effect of increasing CO₂ concentration on the rate of the Calvin cycle. [2 marks]", marks:2, ms:"More CO₂ available as substrate for RuBisCO (1); rate of carbon fixation/Calvin cycle increases (1)"}},
      { id:"b8-010", tier:"triple_H", q:"What happens to the Calvin cycle if the light-dependent reaction stops?", a:"ATP and reduced NADP are no longer produced, so GP cannot be converted to GALP; GP accumulates and RuBP runs out", examQ:{q:"Predict what would happen to the levels of GP and RuBP if light was removed. Explain your answer. [4 marks]", marks:4, ms:"GP would increase/accumulate (1); because it cannot be converted to GALP without ATP/reduced NADP (1); RuBP would decrease (1); because it cannot be regenerated (1)"}},
    ]
  },

  b9: {
    name: "Respiration (Triple)",
    cards: [
      { id:"b9-001", tier:"triple_F", q:"What are the four stages of aerobic respiration?", a:"Glycolysis, link reaction, Krebs cycle, oxidative phosphorylation (electron transport chain)", examQ:{q:"Name the four stages of aerobic respiration in order. [2 marks]", marks:2, ms:"Glycolysis (1); link reaction, Krebs cycle, oxidative phosphorylation/electron transport chain (1)"}},
      { id:"b9-002", tier:"triple_F", q:"Where does glycolysis occur?", a:"In the cytoplasm", examQ:{q:"State where glycolysis takes place and what it produces. [3 marks]", marks:3, ms:"Cytoplasm (1); 2 pyruvate (1); net 2 ATP and 2 reduced NAD (1)"}},
      { id:"b9-003", tier:"triple_F", q:"What happens in glycolysis?", a:"Glucose (6C) is split into two pyruvate molecules (3C each), producing a net gain of 2 ATP and 2 reduced NAD", examQ:{q:"Describe what happens during glycolysis. [3 marks]", marks:3, ms:"Glucose phosphorylated/activated using ATP (1); split into 2 pyruvate (1); net gain of 2 ATP and reduced NAD produced (1)"}},
      { id:"b9-004", tier:"triple_F", q:"Where does the link reaction occur?", a:"In the mitochondrial matrix", examQ:{q:"State where the link reaction occurs and describe what happens. [3 marks]", marks:3, ms:"Mitochondrial matrix (1); pyruvate decarboxylated/CO₂ removed (1); acetyl CoA formed and reduced NAD produced (1)"}},
      { id:"b9-005", tier:"triple_F", q:"What happens in the link reaction?", a:"Pyruvate is decarboxylated (CO₂ removed) and combined with coenzyme A to form acetyl CoA; reduced NAD is produced", examQ:{q:"Explain the role of coenzyme A in the link reaction. [2 marks]", marks:2, ms:"Combines with acetate/2C fragment (1); forms acetyl CoA which enters the Krebs cycle (1)"}},
      { id:"b9-006", tier:"triple_F", q:"Where does the Krebs cycle occur?", a:"In the mitochondrial matrix", examQ:{q:"State where the Krebs cycle occurs. [1 mark]", marks:1, ms:"Mitochondrial matrix (1)"}},
      { id:"b9-007", tier:"triple_F", q:"What are the products of one turn of the Krebs cycle?", a:"2CO₂, 3 reduced NAD, 1 reduced FAD, 1 ATP", examQ:{q:"State the products of one turn of the Krebs cycle. [3 marks]", marks:3, ms:"2CO₂ released (1); 3 reduced NAD and 1 reduced FAD (1); 1 ATP (1)"}},
      { id:"b9-008", tier:"triple_F", q:"Where does oxidative phosphorylation occur?", a:"On the inner mitochondrial membrane (cristae)", examQ:{q:"State where oxidative phosphorylation takes place and explain how ATP is produced. [3 marks]", marks:3, ms:"Inner mitochondrial membrane/cristae (1); electrons from reduced NAD/FAD pass along electron transport chain (1); energy used to pump H⁺ ions, which flow back through ATP synthase producing ATP (1)"}},
      { id:"b9-009", tier:"triple_H", q:"What is the role of oxygen in oxidative phosphorylation?", a:"Oxygen is the final electron acceptor; it combines with hydrogen ions and electrons to form water", examQ:{q:"Explain why aerobic respiration cannot occur without oxygen. [3 marks]", marks:3, ms:"Oxygen is the final electron acceptor (1); accepts electrons and hydrogen ions at end of electron transport chain (1); without oxygen, electron transport chain stops and ATP cannot be produced (1)"}},
      { id:"b9-010", tier:"triple_H", q:"How does the electron transport chain produce ATP?", a:"Electrons from reduced NAD and FAD pass along carriers, releasing energy to pump H⁺ ions across the membrane; H⁺ ions flow back through ATP synthase, driving ATP synthesis (chemiosmosis)", examQ:{q:"Describe the process of chemiosmosis in mitochondria. [4 marks]", marks:4, ms:"Electrons from reduced NAD/FAD pass along electron transport chain (1); energy released pumps H⁺ across inner membrane into intermembrane space (1); H⁺ ions flow back through ATP synthase down concentration gradient (1); drives rotation of ATP synthase producing ATP (1)"}},
      { id:"b9-011", tier:"triple_F", q:"What happens to pyruvate during anaerobic respiration in animals?", a:"Pyruvate is converted to lactate (lactic acid) by lactate dehydrogenase, regenerating NAD", examQ:{q:"Explain why pyruvate is converted to lactate during anaerobic respiration in animals. [3 marks]", marks:3, ms:"No oxygen available as final electron acceptor (1); reduced NAD must be reoxidised to NAD (1); so glycolysis can continue producing ATP (1)"}},
      { id:"b9-012", tier:"triple_F", q:"What happens to pyruvate during anaerobic respiration in yeast?", a:"Pyruvate is decarboxylated to ethanal, then reduced to ethanol; CO₂ is released and NAD is regenerated", examQ:{q:"Describe the process of anaerobic respiration in yeast. [3 marks]", marks:3, ms:"Pyruvate decarboxylated to ethanal/CO₂ released (1); ethanal reduced to ethanol (1); NAD regenerated allowing glycolysis to continue (1)"}},
    ]
  },

  b10: {
    name: "The Nervous System (Triple)",
    cards: [
      { id:"b10-001", tier:"triple_F", q:"What is the structure of a myelinated neurone?", a:"Cell body, dendrites, axon, myelin sheath (made of Schwann cells), nodes of Ranvier, synaptic terminals", examQ:{q:"Describe the structure of a myelinated motor neurone. [4 marks]", marks:4, ms:"Cell body with nucleus (1); dendrites receive signals (1); axon carries impulse away from cell body (1); myelin sheath made of Schwann cells with nodes of Ranvier (1)"}},
      { id:"b10-002", tier:"triple_F", q:"What is the function of the myelin sheath?", a:"Insulates the axon and speeds up nerve impulse transmission by saltatory conduction (impulse jumps between nodes of Ranvier)", examQ:{q:"Explain how the myelin sheath increases the speed of nerve impulse transmission. [3 marks]", marks:3, ms:"Myelin sheath acts as electrical insulator (1); impulse jumps between nodes of Ranvier (1); saltatory conduction is faster than continuous conduction (1)"}},
      { id:"b10-003", tier:"triple_F", q:"What is a resting potential?", a:"The potential difference across the axon membrane when not transmitting an impulse, typically -70mV (inside negative relative to outside)", examQ:{q:"Describe how the resting potential is maintained across a neurone membrane. [3 marks]", marks:3, ms:"More Na⁺ outside, more K⁺ inside (1); maintained by sodium-potassium pump (1); membrane more permeable to K⁺ so some leaks out making inside negative (-70mV) (1)"}},
      { id:"b10-004", tier:"triple_F", q:"What happens during depolarisation?", a:"Na⁺ channels open, Na⁺ rushes into the axon, making the inside more positive (action potential reaches +40mV)", examQ:{q:"Explain what happens during depolarisation of a neurone. [3 marks]", marks:3, ms:"Stimulus causes Na⁺ channels to open (1); Na⁺ ions diffuse into axon down concentration gradient (1); inside becomes less negative/positive, reaching +40mV (1)"}},
      { id:"b10-005", tier:"triple_F", q:"What happens during repolarisation?", a:"Na⁺ channels close, K⁺ channels open, K⁺ rushes out, restoring negative charge inside the axon", examQ:{q:"Describe repolarisation of a neurone membrane. [3 marks]", marks:3, ms:"Na⁺ channels close (1); K⁺ channels open (1); K⁺ diffuses out restoring negative charge inside (1)"}},
      { id:"b10-006", tier:"triple_H", q:"What is the refractory period and why is it important?", a:"The period after an action potential when the membrane cannot be depolarised again; it ensures impulses travel in one direction only and limits impulse frequency", examQ:{q:"Explain the importance of the refractory period in nerve impulse transmission. [3 marks]", marks:3, ms:"Period when membrane cannot be excited again (1); ensures impulses travel in one direction only (1); limits the frequency of impulses (1)"}},
      { id:"b10-007", tier:"triple_F", q:"What is a synapse?", a:"A junction between two neurones where nerve impulses are transmitted chemically via neurotransmitters across the synaptic cleft", examQ:{q:"Describe how a nerve impulse is transmitted across a synapse. [5 marks]", marks:5, ms:"Action potential arrives at presynaptic membrane (1); Ca²⁺ ions enter (1); vesicles fuse with membrane releasing neurotransmitter (1); neurotransmitter diffuses across synaptic cleft (1); binds to receptors on postsynaptic membrane causing depolarisation (1)"}},
      { id:"b10-008", tier:"triple_F", q:"How is the neurotransmitter removed from the synapse?", a:"It is broken down by enzymes in the synaptic cleft or reabsorbed by the presynaptic neurone (reuptake)", examQ:{q:"Explain why it is important that neurotransmitters are removed from the synaptic cleft after transmission. [2 marks]", marks:2, ms:"Prevents continuous stimulation of postsynaptic neurone (1); allows synapse to reset for next impulse (1)"}},
      { id:"b10-009", tier:"triple_H", q:"How do drugs affect synaptic transmission?", a:"Some drugs mimic neurotransmitters and bind to receptors (agonists); others block receptors preventing neurotransmitter binding (antagonists); some inhibit enzyme breakdown of neurotransmitters", examQ:{q:"Explain how a drug that inhibits the enzyme that breaks down neurotransmitters would affect synaptic transmission. [3 marks]", marks:3, ms:"Neurotransmitter remains in synaptic cleft longer (1); continues to bind to postsynaptic receptors (1); prolonged/enhanced stimulation of postsynaptic neurone (1)"}},
      { id:"b10-010", tier:"triple_F", q:"What are the three types of neurones?", a:"Sensory neurones (receptor to CNS), relay neurones (within CNS), motor neurones (CNS to effector)", examQ:{q:"Compare the functions of sensory, relay and motor neurones. [3 marks]", marks:3, ms:"Sensory: carry impulses from receptors to CNS (1); relay: carry impulses within CNS (1); motor: carry impulses from CNS to effectors (1)"}},
    ]
  },

  b11: {
    name: "Hormonal Coordination (Triple)",
    cards: [
      { id:"b11-001", tier:"triple_F", q:"What is the structure of the human kidney?", a:"Cortex (outer), medulla (inner), renal pelvis, ureter; contains nephrons which filter blood", examQ:{q:"Label and describe the main regions of the kidney. [3 marks]", marks:3, ms:"Cortex - outer region where filtration occurs (1); medulla - inner region containing loops of Henle (1); renal pelvis - collects urine, leads to ureter (1)"}},
      { id:"b11-002", tier:"triple_F", q:"What is ultrafiltration?", a:"The process in the glomerulus where high blood pressure forces small molecules (glucose, urea, ions, water) out of the blood into the Bowman's capsule", examQ:{q:"Explain how ultrafiltration occurs in the kidney. [4 marks]", marks:4, ms:"Blood enters glomerulus under high pressure (1); glomerulus is a knot of capillaries in Bowman's capsule (1); small molecules forced through capillary walls and podocytes (1); large molecules e.g. proteins remain in blood (1)"}},
      { id:"b11-003", tier:"triple_F", q:"What is selective reabsorption?", a:"The process by which useful substances (glucose, some ions, water) are reabsorbed from the filtrate back into the blood in the proximal convoluted tubule", examQ:{q:"Explain how selective reabsorption occurs in the proximal convoluted tubule. [4 marks]", marks:4, ms:"Glucose reabsorbed by active transport (1); requires ATP/energy (1); water reabsorbed by osmosis (1); some ions reabsorbed by active transport (1)"}},
      { id:"b11-004", tier:"triple_F", q:"What is the role of ADH in osmoregulation?", a:"ADH (antidiuretic hormone) from the pituitary gland increases the permeability of the collecting duct to water, so more water is reabsorbed and less urine is produced", examQ:{q:"Explain how ADH controls water reabsorption in the kidney. [4 marks]", marks:4, ms:"ADH released from pituitary gland (1); when blood water potential is low (1); ADH increases permeability of collecting duct to water (1); more water reabsorbed by osmosis, producing concentrated urine (1)"}},
      { id:"b11-005", tier:"triple_H", q:"How does the loop of Henle create a concentration gradient?", a:"The descending limb is permeable to water (water leaves by osmosis); the ascending limb actively pumps Na⁺ and Cl⁻ out; this creates a high solute concentration in the medulla, enabling water reabsorption", examQ:{q:"Explain how the loop of Henle creates a concentration gradient in the medulla. [4 marks]", marks:4, ms:"Descending limb permeable to water, water leaves by osmosis (1); ascending limb impermeable to water (1); Na⁺/Cl⁻ actively pumped out of ascending limb (1); builds up high solute concentration in medulla enabling water reabsorption (1)"}},
      { id:"b11-006", tier:"triple_F", q:"What happens to urea in the kidney?", a:"Urea is filtered out of the blood in the glomerulus, passes through the nephron and is excreted in urine; it is not reabsorbed", examQ:{q:"Describe the fate of urea as it passes through the nephron. [3 marks]", marks:3, ms:"Filtered from blood in glomerulus into Bowman's capsule (1); passes through nephron tubules (1); not reabsorbed, excreted in urine (1)"}},
      { id:"b11-007", tier:"triple_F", q:"What is dialysis and how does it work?", a:"Dialysis is a treatment for kidney failure; blood is passed over a partially permeable membrane against dialysis fluid; urea and excess ions diffuse out while useful substances are retained", examQ:{q:"Explain how a dialysis machine removes urea from the blood. [4 marks]", marks:4, ms:"Blood passed over partially permeable membrane (1); dialysis fluid on other side contains no urea (1); urea diffuses down concentration gradient into dialysis fluid (1); glucose and useful ions at correct concentration so not lost (1)"}},
      { id:"b11-008", tier:"triple_F", q:"What are the advantages of a kidney transplant over dialysis?", a:"Transplant is a permanent solution, better quality of life, no need for regular dialysis sessions, more cost-effective long term", examQ:{q:"Evaluate kidney transplantation as a treatment for kidney failure compared to dialysis. [4 marks]", marks:4, ms:"Transplant advantage: permanent/no regular treatment needed (1); better quality of life (1); Disadvantage: risk of rejection/need immunosuppressants (1); dialysis disadvantage: time-consuming/3 sessions per week (1)"}},
      { id:"b11-009", tier:"triple_H", q:"How do aquaporins contribute to water reabsorption?", a:"Aquaporins are water channel proteins in the collecting duct membrane; ADH causes more aquaporins to be inserted into the membrane, increasing water permeability and reabsorption", examQ:{q:"Explain the role of aquaporins in the action of ADH. [3 marks]", marks:3, ms:"Aquaporins are water channel proteins (1); ADH causes insertion of aquaporins into collecting duct membrane (1); increases permeability to water so more water reabsorbed (1)"}},
    ]
  },

  b12: {
    name: "Genetics (Triple)",
    cards: [
      { id:"b12-001", tier:"triple_F", q:"What is the difference between continuous and discontinuous variation?", a:"Continuous variation has a range of values with no distinct categories (e.g. height, mass); discontinuous variation has distinct categories with no intermediates (e.g. blood group, tongue rolling)", examQ:{q:"Distinguish between continuous and discontinuous variation, giving one example of each. [4 marks]", marks:4, ms:"Continuous: range of values/no distinct groups (1); example e.g. height/mass/foot size (1); discontinuous: distinct categories/no intermediates (1); example e.g. blood group/tongue rolling/attached earlobes (1)"}},
      { id:"b12-002", tier:"triple_F", q:"What causes continuous variation?", a:"Both genes and environment contribute; polygenic inheritance (many genes) produces a wide range of phenotypes", examQ:{q:"Explain why height shows continuous variation. [3 marks]", marks:3, ms:"Controlled by many genes/polygenic (1); environment also affects height e.g. diet/illness (1); interaction of genes and environment produces wide range of values (1)"}},
      { id:"b12-003", tier:"triple_F", q:"What is a mutation?", a:"A change in the DNA base sequence of a gene or chromosome", examQ:{q:"Explain what is meant by a gene mutation and state one factor that can increase the rate of mutations. [3 marks]", marks:3, ms:"A change in the DNA/base sequence of a gene (1); can alter the amino acid sequence of a protein (1); mutagen e.g. UV radiation/ionising radiation/certain chemicals (1)"}},
      { id:"b12-004", tier:"triple_F", q:"What is the difference between a substitution and a deletion mutation?", a:"Substitution: one base is replaced by another (may or may not change the amino acid); deletion: a base is removed, causing a frameshift that alters all subsequent amino acids", examQ:{q:"Compare the effects of a substitution mutation and a deletion mutation on a protein. [4 marks]", marks:4, ms:"Substitution replaces one base (1); may change one amino acid or have no effect due to degenerate code (1); deletion removes a base causing frameshift (1); alters all amino acids after the mutation, likely non-functional protein (1)"}},
      { id:"b12-005", tier:"triple_H", q:"Why does a deletion mutation have a greater effect than a substitution?", a:"A deletion causes a frameshift — it shifts the reading frame of all codons after the mutation, changing every subsequent amino acid; a substitution only affects one codon", examQ:{q:"Explain why a deletion mutation is usually more harmful than a substitution mutation. [3 marks]", marks:3, ms:"Deletion causes a frameshift (1); all codons after the mutation are altered (1); substitution only affects one codon so fewer amino acids changed (1)"}},
      { id:"b12-006", tier:"triple_F", q:"What is the genetic code?", a:"The sequence of bases in DNA/mRNA that codes for amino acids; it is universal, non-overlapping and degenerate (redundant)", examQ:{q:"State three features of the genetic code. [3 marks]", marks:3, ms:"Universal (same in all organisms) (1); non-overlapping (each base only read once) (1); degenerate/redundant (more than one codon codes for each amino acid) (1)"}},
      { id:"b12-007", tier:"triple_F", q:"What is transcription?", a:"The process by which the DNA template strand is used to make a complementary mRNA strand in the nucleus, using RNA polymerase", examQ:{q:"Describe the process of transcription. [4 marks]", marks:4, ms:"DNA double helix unwinds/hydrogen bonds break (1); RNA polymerase binds to template strand (1); complementary mRNA strand synthesised using free RNA nucleotides (1); mRNA leaves nucleus through nuclear pore (1)"}},
      { id:"b12-008", tier:"triple_F", q:"What is translation?", a:"The process by which the mRNA sequence is used to assemble a polypeptide chain at the ribosome, using tRNA to bring specific amino acids", examQ:{q:"Describe the process of translation. [5 marks]", marks:5, ms:"mRNA binds to ribosome (1); tRNA with complementary anticodon brings specific amino acid (1); codon-anticodon base pairing (1); amino acids joined by peptide bonds (1); ribosome moves along mRNA until stop codon reached (1)"}},
      { id:"b12-009", tier:"triple_H", q:"What is the role of tRNA in translation?", a:"tRNA carries specific amino acids to the ribosome; the anticodon on tRNA is complementary to the codon on mRNA, ensuring the correct amino acid is added to the polypeptide chain", examQ:{q:"Explain the role of tRNA in translation. [3 marks]", marks:3, ms:"tRNA carries specific amino acid (1); anticodon on tRNA is complementary to mRNA codon (1); amino acid added to growing polypeptide chain (1)"}},
      { id:"b12-010", tier:"triple_F", q:"What is epigenetics?", a:"The study of changes in gene expression that do not involve changes to the DNA sequence, e.g. DNA methylation and histone modification", examQ:{q:"Explain what is meant by epigenetics and give one example of an epigenetic change. [3 marks]", marks:3, ms:"Changes in gene expression without changes to DNA sequence (1); heritable changes (1); example: DNA methylation/histone acetylation (1)"}},
    ]
  },

  b13: {
    name: "Evolution (Triple)",
    cards: [
      { id:"b13-001", tier:"triple_F", q:"What is speciation?", a:"The formation of new species when populations become reproductively isolated and evolve separately due to natural selection acting on different variations", examQ:{q:"Explain how speciation can occur through geographical isolation. [5 marks]", marks:5, ms:"Population separated by geographical barrier (1); no interbreeding/gene flow between populations (1); different mutations arise in each population (1); different selection pressures in each environment (1); populations diverge until they can no longer interbreed = new species (1)"}},
      { id:"b13-002", tier:"triple_F", q:"What is the difference between allopatric and sympatric speciation?", a:"Allopatric: geographic isolation separates populations; sympatric: speciation occurs within the same geographic area due to reproductive isolation (e.g. different mating seasons)", examQ:{q:"Distinguish between allopatric and sympatric speciation. [4 marks]", marks:4, ms:"Allopatric: geographic/physical barrier separates populations (1); prevents gene flow between populations (1); sympatric: populations in same area (1); reproductive isolation by other means e.g. different breeding seasons/behaviours (1)"}},
      { id:"b13-003", tier:"triple_F", q:"What is the Hardy-Weinberg principle?", a:"In a large, randomly mating population with no selection, mutation, migration or genetic drift, allele and genotype frequencies remain constant from generation to generation", examQ:{q:"State the conditions required for the Hardy-Weinberg equilibrium to apply. [4 marks]", marks:4, ms:"Large population (1); random mating (1); no natural selection (1); no mutation/migration/genetic drift (1)"}},
      { id:"b13-004", tier:"triple_H", q:"How are Hardy-Weinberg equations used?", a:"p + q = 1 (allele frequencies) and p² + 2pq + q² = 1 (genotype frequencies), where p = dominant allele frequency, q = recessive allele frequency", examQ:{q:"In a population, 9% of individuals show a recessive phenotype. Calculate the frequency of the dominant allele. Show your working. [3 marks]", marks:3, ms:"q² = 0.09 so q = 0.3 (1); p + q = 1 so p = 0.7 (1); frequency of dominant allele = 0.7 (1)"}},
      { id:"b13-005", tier:"triple_F", q:"What is genetic drift?", a:"Random changes in allele frequencies in a population, particularly significant in small populations where chance events can dramatically alter gene pools", examQ:{q:"Explain how genetic drift can lead to evolution in small populations. [3 marks]", marks:3, ms:"Random changes in allele frequencies (1); in small populations chance events have greater effect (1); can cause loss of alleles or fixation of alleles regardless of their selective advantage (1)"}},
      { id:"b13-006", tier:"triple_F", q:"What is the bottleneck effect?", a:"A sharp reduction in population size due to a catastrophic event; the surviving population has reduced genetic diversity and allele frequencies may differ from the original population", examQ:{q:"Explain how a bottleneck event can affect the genetic diversity of a population. [3 marks]", marks:3, ms:"Catastrophic event dramatically reduces population size (1); survivors may not represent original allele frequencies (1); reduced genetic diversity in resulting population (1)"}},
      { id:"b13-007", tier:"triple_F", q:"What is the founder effect?", a:"When a small group of individuals establishes a new population, the new population has low genetic diversity and allele frequencies that reflect the founders, not the original population", examQ:{q:"Explain the founder effect and give an example. [3 marks]", marks:3, ms:"Small group separates from main population to found new population (1); low genetic diversity as only founders' alleles present (1); example: island colonisation/isolated religious communities (1)"}},
      { id:"b13-008", tier:"triple_H", q:"How does directional selection differ from stabilising selection?", a:"Directional selection favours one extreme phenotype, shifting the population mean; stabilising selection favours the intermediate phenotype, reducing variation around the mean", examQ:{q:"Compare directional and stabilising natural selection. [4 marks]", marks:4, ms:"Directional: one extreme phenotype favoured (1); population mean shifts over time (1); stabilising: intermediate phenotype favoured (1); variation reduced, mean stays same (1)"}},
      { id:"b13-009", tier:"triple_H", q:"What is disruptive selection?", a:"A form of natural selection where both extreme phenotypes are favoured over the intermediate, leading to increased variation and potentially speciation", examQ:{q:"Explain how disruptive selection can lead to speciation. [4 marks]", marks:4, ms:"Both extreme phenotypes have selective advantage (1); intermediate phenotypes selected against (1); population splits into two groups with different phenotypes (1); may eventually lead to reproductive isolation and speciation (1)"}},
    ]
  },

  b14: {
    name: "Ecosystems (Triple)",
    cards: [
      { id:"b14-001", tier:"triple_F", q:"What is the difference between a habitat and a niche?", a:"A habitat is where an organism lives; a niche is the role an organism plays in its ecosystem, including what it eats, when it is active, and how it interacts with other organisms", examQ:{q:"Distinguish between a habitat and an ecological niche. [4 marks]", marks:4, ms:"Habitat is the physical place where an organism lives (1); niche includes the organism's role in the ecosystem (1); what it eats/when active/interactions with other species (1); no two species can occupy exactly the same niche (1)"}},
      { id:"b14-002", tier:"triple_F", q:"What is the competitive exclusion principle?", a:"No two species can occupy the same niche in the same habitat indefinitely; one species will outcompete and exclude the other", examQ:{q:"Explain the competitive exclusion principle. [3 marks]", marks:3, ms:"Two species cannot occupy the same niche (1); they compete for the same resources (1); one species outcompetes the other leading to exclusion/local extinction (1)"}},
      { id:"b14-003", tier:"triple_F", q:"What is primary succession?", a:"The colonisation of bare rock or new land by pioneer species, gradually building soil and allowing more complex communities to develop until a climax community is reached", examQ:{q:"Describe the process of primary succession on bare rock. [5 marks]", marks:5, ms:"Pioneer species e.g. lichens colonise bare rock (1); break down rock and add organic matter forming thin soil (1); mosses and ferns colonise (1); larger plants replace smaller ones as soil deepens (1); climax community reached e.g. deciduous woodland (1)"}},
      { id:"b14-004", tier:"triple_F", q:"What is the difference between primary and secondary succession?", a:"Primary succession starts on bare rock/new land with no soil; secondary succession occurs where soil already exists but vegetation has been removed (e.g. after fire or farming)", examQ:{q:"Compare primary and secondary succession. [4 marks]", marks:4, ms:"Primary: starts on bare substrate with no soil (1); secondary: soil already present (1); secondary succession faster as nutrients already available (1); both end in climax community (1)"}},
      { id:"b14-005", tier:"triple_F", q:"What is a climax community?", a:"The final stable community reached at the end of succession, where species composition remains relatively constant unless disturbed", examQ:{q:"Explain what is meant by a climax community. [2 marks]", marks:2, ms:"Final/stable community at end of succession (1); species composition remains constant unless disturbed (1)"}},
      { id:"b14-006", tier:"triple_H", q:"How does the nitrogen cycle contribute to ecosystem productivity?", a:"Nitrogen is essential for protein and nucleic acid synthesis; nitrogen-fixing bacteria convert N₂ to ammonia; nitrifying bacteria convert ammonia to nitrates; denitrifying bacteria return N₂ to atmosphere", examQ:{q:"Explain the roles of bacteria in the nitrogen cycle. [5 marks]", marks:5, ms:"Nitrogen-fixing bacteria convert N₂ to ammonia/ammonium ions (1); found in soil or root nodules of legumes (1); nitrifying bacteria convert ammonia to nitrites then nitrates (1); denitrifying bacteria convert nitrates back to N₂ (1); decomposers break down proteins releasing ammonia (1)"}},
      { id:"b14-007", tier:"triple_F", q:"What is biomass and how is it measured?", a:"Biomass is the mass of living material in organisms; it can be measured as fresh mass, dry mass, or energy content; dry mass is most accurate as it removes water variability", examQ:{q:"Explain why dry mass is a more reliable measure of biomass than fresh mass. [2 marks]", marks:2, ms:"Fresh mass includes water which varies (1); dry mass removes water giving consistent measure of organic material (1)"}},
      { id:"b14-008", tier:"triple_H", q:"How is energy transferred between trophic levels?", a:"Only about 10% of energy is transferred between each trophic level; energy is lost through respiration, heat, movement, excretion and uneaten material", examQ:{q:"Explain why only about 10% of energy is transferred from one trophic level to the next. [4 marks]", marks:4, ms:"Energy lost in respiration as heat (1); energy used for movement/metabolic processes (1); material not consumed/eaten (1); energy lost in excretion/faeces (1)"}},
      { id:"b14-009", tier:"triple_F", q:"What is eutrophication?", a:"Excess nutrients (especially nitrates and phosphates) enter water, causing algal bloom; algae block light, plants die, decomposers increase using up oxygen, causing death of aquatic organisms", examQ:{q:"Describe the process of eutrophication and its effects on a freshwater ecosystem. [5 marks]", marks:5, ms:"Excess nitrates/phosphates enter water from fertilisers/sewage (1); algal bloom on surface (1); algae block light, aquatic plants die (1); decomposers break down dead material, using up oxygen (1); fish and other aquatic organisms die due to lack of oxygen (1)"}},
    ]
  },

  b15: {
    name: "Microbiology (Triple)",
    cards: [
      { id:"b15-001", tier:"triple_F", q:"What is the structure of a bacterium?", a:"Cell wall, cell membrane, cytoplasm, circular DNA (nucleoid region), plasmids, ribosomes; no nucleus or membrane-bound organelles", examQ:{q:"Describe the structure of a bacterial cell and state how it differs from a eukaryotic cell. [4 marks]", marks:4, ms:"Has cell wall, cell membrane, cytoplasm, ribosomes (1); circular DNA not in nucleus (1); has plasmids (1); no membrane-bound organelles/nucleus (1)"}},
      { id:"b15-002", tier:"triple_F", q:"What is binary fission?", a:"Asexual reproduction in bacteria where the circular DNA replicates, the cell elongates and divides into two identical daughter cells", examQ:{q:"Describe the process of binary fission in bacteria. [3 marks]", marks:3, ms:"Circular DNA replicates (1); cell elongates (1); cell divides into two genetically identical daughter cells (1)"}},
      { id:"b15-003", tier:"triple_F", q:"What factors affect the growth rate of bacteria?", a:"Temperature, pH, nutrient availability, oxygen levels (for aerobic bacteria), water availability", examQ:{q:"Explain how temperature affects the growth rate of bacteria. [3 marks]", marks:3, ms:"Low temperature: enzymes have less kinetic energy, slow growth (1); optimum temperature: maximum enzyme activity, fastest growth (1); high temperature: enzymes denature, growth stops (1)"}},
      { id:"b15-004", tier:"triple_F", q:"What are the four phases of bacterial growth in a closed culture?", a:"Lag phase (adaptation), exponential/log phase (rapid growth), stationary phase (growth = death), decline/death phase (death > growth)", examQ:{q:"Describe the four phases of bacterial growth and explain what causes each. [4 marks]", marks:4, ms:"Lag phase: bacteria adapting, producing enzymes (1); exponential phase: rapid reproduction, nutrients plentiful (1); stationary phase: nutrients limiting, waste builds up (1); death phase: nutrients exhausted, toxic waste accumulates (1)"}},
      { id:"b15-005", tier:"triple_F", q:"What is aseptic technique and why is it used?", a:"Aseptic technique is a set of procedures used to prevent contamination of cultures with unwanted microorganisms, including flaming loops, using sterile equipment and working near a Bunsen flame", examQ:{q:"Describe the aseptic techniques used when culturing bacteria. [4 marks]", marks:4, ms:"Sterilise inoculating loop by flaming (1); work near Bunsen burner to create updraft preventing contamination (1); use sterile agar plates (1); seal plates with tape but not completely (allow gas exchange) and incubate inverted (1)"}},
      { id:"b15-006", tier:"triple_F", q:"How can the effect of antibiotics on bacteria be tested?", a:"Using the disc diffusion method: antibiotic-soaked discs are placed on an agar plate inoculated with bacteria; after incubation, the zone of inhibition (clear area) around each disc indicates antibiotic effectiveness", examQ:{q:"Describe how you would use the disc diffusion method to compare the effectiveness of two antibiotics. [5 marks]", marks:5, ms:"Inoculate agar plate with bacterial culture (1); place antibiotic discs on agar surface (1); incubate at 25°C (1); measure zones of inhibition (clear areas) around each disc (1); larger zone = more effective antibiotic (1)"}},
      { id:"b15-007", tier:"triple_H", q:"How does antibiotic resistance develop in bacteria?", a:"Random mutations produce resistant bacteria; antibiotics kill susceptible bacteria, leaving resistant ones to reproduce (natural selection); resistant alleles increase in frequency in the population", examQ:{q:"Explain how antibiotic resistance develops in a bacterial population. [5 marks]", marks:5, ms:"Random mutation produces antibiotic-resistant bacteria (1); antibiotic kills susceptible bacteria (1); resistant bacteria survive and reproduce (1); resistant allele passed to offspring (1); frequency of resistant allele increases in population over generations (1)"}},
      { id:"b15-008", tier:"triple_F", q:"What is a virus and how does it replicate?", a:"A virus is a non-cellular particle with genetic material (DNA or RNA) surrounded by a protein coat (capsid); it replicates by injecting its genetic material into a host cell, hijacking the cell's machinery to produce new viruses", examQ:{q:"Describe how a virus replicates inside a host cell. [4 marks]", marks:4, ms:"Virus attaches to specific receptor on host cell (1); injects genetic material into host cell (1); host cell's ribosomes/enzymes used to replicate viral DNA and produce viral proteins (1); new viruses assembled and released, often destroying host cell (1)"}},
      { id:"b15-009", tier:"triple_H", q:"What is the difference between the lytic and lysogenic cycles?", a:"Lytic cycle: virus immediately replicates and destroys host cell; lysogenic cycle: viral DNA integrates into host chromosome (prophage) and is replicated with the host for many generations before entering the lytic cycle", examQ:{q:"Compare the lytic and lysogenic cycles of bacteriophage replication. [4 marks]", marks:4, ms:"Lytic: virus immediately takes over host cell machinery (1); host cell lyses/bursts releasing new viruses (1); lysogenic: viral DNA integrates into host chromosome as prophage (1); replicated with host DNA until triggered to enter lytic cycle (1)"}},
    ]
  }
};

// Count cards
let total = 0;
Object.entries(TRIPLE_BIOLOGY).forEach(([topic, data]) => {
  console.log(`${topic} (${data.name}): ${data.cards.length} cards`);
  total += data.cards.length;
});
console.log(`Total Triple Biology cards: ${total}`);

const TRIPLE_CHEMISTRY = {

  c11: {
    name: "Titration & Volumetric Analysis (Triple)",
    cards: [
      { id:"c11-001", tier:"triple_F", q:"What is a titration?", a:"A technique used to find the exact volume of one solution needed to react with a known volume of another solution, used to find unknown concentrations", examQ:{q:"Describe how you would carry out an acid-base titration to find the concentration of a sodium hydroxide solution using hydrochloric acid of known concentration. [5 marks]", marks:5, ms:"Fill burette with HCl of known concentration (1); pipette fixed volume of NaOH into conical flask (1); add indicator e.g. phenolphthalein (1); add HCl slowly until colour change (endpoint) (1); record volume used and repeat for concordant results (1)"}},
      { id:"c11-002", tier:"triple_F", q:"What is the endpoint of a titration?", a:"The point at which the indicator changes colour permanently, showing the reaction is complete (equivalence point reached)", examQ:{q:"Explain what is meant by the endpoint of a titration and how it is identified. [2 marks]", marks:2, ms:"Point at which reaction is complete (1); identified by permanent colour change of indicator (1)"}},
      { id:"c11-003", tier:"triple_F", q:"How do you calculate concentration from titration results?", a:"Use: moles = concentration × volume; find moles of known solution, use mole ratio from equation to find moles of unknown, then concentration = moles ÷ volume", examQ:{q:"25cm³ of NaOH required 20cm³ of 0.1 mol/dm³ HCl for neutralisation. Calculate the concentration of NaOH. [3 marks]", marks:3, ms:"Moles HCl = 0.1 × 0.020 = 0.002 mol (1); mole ratio 1:1 so moles NaOH = 0.002 mol (1); concentration NaOH = 0.002 ÷ 0.025 = 0.08 mol/dm³ (1)"}},
      { id:"c11-004", tier:"triple_H", q:"What is a back titration and when is it used?", a:"A back titration is used when direct titration is not possible (e.g. the analyte is insoluble); an excess of one reagent is added, then the unreacted excess is titrated to find how much reacted", examQ:{q:"Explain when a back titration would be used and describe the principle. [3 marks]", marks:3, ms:"Used when direct titration not possible e.g. insoluble solid (1); excess of known reagent added (1); unreacted excess titrated to find amount that reacted with sample (1)"}},
      { id:"c11-005", tier:"triple_F", q:"What indicators are used in acid-base titrations?", a:"Methyl orange (changes red to yellow, used for strong acid/weak base titrations); phenolphthalein (changes colourless to pink, used for strong base/weak acid titrations)", examQ:{q:"State which indicator you would use for a titration between a strong acid and a weak base and explain your choice. [2 marks]", marks:2, ms:"Methyl orange (1); gives sharp colour change at equivalence point for strong acid/weak base titration (1)"}},
    ]
  },

  c12: {
    name: "Organic Chemistry (Triple)",
    cards: [
      { id:"c12-001", tier:"triple_F", q:"What is a homologous series?", a:"A family of compounds with the same functional group, same general formula, and similar chemical properties, with each member differing by CH₂", examQ:{q:"State three characteristics of a homologous series. [3 marks]", marks:3, ms:"Same functional group (1); same general formula (1); each member differs by CH₂/14 mass units (1)"}},
      { id:"c12-002", tier:"triple_F", q:"What are the functional groups of alcohols, carboxylic acids and esters?", a:"Alcohols: -OH; Carboxylic acids: -COOH; Esters: -COO-", examQ:{q:"Draw and name the functional groups of alcohols and carboxylic acids. [2 marks]", marks:2, ms:"Alcohol: -OH (hydroxyl group) (1); carboxylic acid: -COOH (carboxyl group) (1)"}},
      { id:"c12-003", tier:"triple_F", q:"How are esters formed?", a:"Esters are formed by the reaction of a carboxylic acid with an alcohol in the presence of an acid catalyst (esterification); water is also produced", examQ:{q:"Write the equation for the formation of ethyl ethanoate from ethanol and ethanoic acid. [3 marks]", marks:3, ms:"CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O (1); acid catalyst required (1); reversible reaction (1)"}},
      { id:"c12-004", tier:"triple_F", q:"What are the properties and uses of esters?", a:"Esters have pleasant fruity smells; they are used as flavourings, perfumes and solvents", examQ:{q:"State two uses of esters and explain why they are suitable for these uses. [4 marks]", marks:4, ms:"Flavourings/perfumes: pleasant fruity/sweet smell (1); volatile so aroma detected easily (1); solvents: dissolve non-polar substances (1); evaporate quickly and don't react with contents (1)"}},
      { id:"c12-005", tier:"triple_F", q:"What is addition polymerisation?", a:"A reaction where many small unsaturated monomers (alkenes) join together to form a long polymer chain; the double bond opens to form single bonds", examQ:{q:"Explain how poly(ethene) is formed from ethene monomers. [3 marks]", marks:3, ms:"Ethene monomers have C=C double bond (1); double bond opens during polymerisation (1); monomers join together to form long chain poly(ethene) (1)"}},
      { id:"c12-006", tier:"triple_F", q:"What is condensation polymerisation?", a:"A reaction where monomers join together releasing a small molecule (usually water or HCl) at each bond; produces polyesters, polyamides and polypeptides", examQ:{q:"Compare addition and condensation polymerisation. [4 marks]", marks:4, ms:"Addition: uses unsaturated monomers/alkenes (1); no small molecule lost (1); condensation: uses monomers with two functional groups (1); small molecule e.g. water released at each bond (1)"}},
      { id:"c12-007", tier:"triple_F", q:"How is nylon formed?", a:"Nylon is a polyamide formed by condensation polymerisation between a diamine and a dicarboxylic acid; water is released at each amide bond (-CO-NH-)", examQ:{q:"Describe the formation of nylon. [3 marks]", marks:3, ms:"Condensation polymerisation (1); between diamine and dicarboxylic acid (1); amide bonds (-CO-NH-) formed with water released (1)"}},
      { id:"c12-008", tier:"triple_F", q:"How is polyester (Terylene) formed?", a:"Polyester is formed by condensation polymerisation between a diol and a dicarboxylic acid; ester bonds (-CO-O-) form with water released", examQ:{q:"Describe the formation of a polyester. [3 marks]", marks:3, ms:"Condensation polymerisation (1); between diol and dicarboxylic acid (1); ester bonds (-COO-) formed, water released (1)"}},
      { id:"c12-009", tier:"triple_H", q:"What is hydrolysis of a polymer?", a:"Breaking down a polymer by reaction with water; condensation polymers (polyesters, polyamides) can be hydrolysed, but addition polymers cannot", examQ:{q:"Explain why polyesters can be hydrolysed but poly(ethene) cannot. [3 marks]", marks:3, ms:"Polyesters have ester bonds which can react with water (1); hydrolysis breaks these bonds regenerating monomers (1); poly(ethene) has only C-C bonds which do not react with water (1)"}},
      { id:"c12-010", tier:"triple_F", q:"What are the products of complete and incomplete combustion of hydrocarbons?", a:"Complete: CO₂ and H₂O; Incomplete: CO (carbon monoxide), carbon (soot) and H₂O; incomplete combustion occurs with insufficient oxygen", examQ:{q:"Explain why incomplete combustion of hydrocarbons is dangerous. [3 marks]", marks:3, ms:"Produces carbon monoxide (1); CO is toxic/colourless/odourless (1); binds to haemoglobin preventing oxygen transport (1)"}},
    ]
  },

  c13: {
    name: "Chemical Analysis (Triple)",
    cards: [
      { id:"c13-001", tier:"triple_F", q:"What is chromatography used for?", a:"To separate and identify mixtures of substances based on their different solubilities in a solvent (mobile phase) and how strongly they are attracted to the stationary phase", examQ:{q:"Explain how paper chromatography separates a mixture of dyes. [4 marks]", marks:4, ms:"Solvent (mobile phase) travels up paper (stationary phase) (1); components dissolve in solvent and move with it (1); components with greater solubility/less attraction to paper travel further (1); different components separate at different distances (1)"}},
      { id:"c13-002", tier:"triple_F", q:"What is the Rf value?", a:"Rf = distance moved by substance ÷ distance moved by solvent; used to identify substances by comparing with known values", examQ:{q:"A substance moved 4.5 cm and the solvent front moved 9.0 cm. Calculate the Rf value and explain how this could be used to identify the substance. [3 marks]", marks:3, ms:"Rf = 4.5 ÷ 9.0 = 0.5 (1); compare Rf value to known reference values (1); matching Rf value suggests same substance (1)"}},
      { id:"c13-003", tier:"triple_F", q:"What is gas chromatography (GC)?", a:"A technique for separating volatile mixtures; the sample is vaporised and carried by an inert gas through a column; components separate based on their different boiling points and interactions with the column", examQ:{q:"Describe how gas chromatography separates a mixture. [4 marks]", marks:4, ms:"Sample vaporised and carried by inert carrier gas (1); passes through column containing stationary phase (1); components with lower boiling points/less interaction with column emerge first (1); detector records when components emerge (retention time) (1)"}},
      { id:"c13-004", tier:"triple_F", q:"How can GC be combined with mass spectrometry?", a:"GC-MS: separated components from GC enter a mass spectrometer which identifies them by their mass spectrum; very sensitive and can identify unknown compounds", examQ:{q:"Explain the advantage of combining gas chromatography with mass spectrometry (GC-MS). [3 marks]", marks:3, ms:"GC separates components of mixture (1); MS identifies each component by its mass spectrum (1); can identify unknown compounds in very small quantities (1)"}},
      { id:"c13-005", tier:"triple_F", q:"What is a flame test and what colours indicate which metals?", a:"A flame test identifies metal ions: Li⁺ = red, Na⁺ = yellow, K⁺ = lilac, Ca²⁺ = orange-red, Cu²⁺ = green", examQ:{q:"Describe how to carry out a flame test and state the colours produced by sodium and copper ions. [3 marks]", marks:3, ms:"Clean wire loop in HCl, hold in flame (1); dip in sample, hold in blue Bunsen flame (1); sodium = yellow flame; copper = green flame (1)"}},
      { id:"c13-006", tier:"triple_F", q:"How are halide ions identified?", a:"Add dilute nitric acid then silver nitrate solution: Cl⁻ = white precipitate (AgCl); Br⁻ = cream precipitate (AgBr); I⁻ = yellow precipitate (AgI)", examQ:{q:"Describe the test for chloride ions in solution and state the expected result. [3 marks]", marks:3, ms:"Add dilute nitric acid (1); add silver nitrate solution (1); white precipitate of silver chloride forms (1)"}},
      { id:"c13-007", tier:"triple_F", q:"How are sulfate ions identified?", a:"Add dilute hydrochloric acid then barium chloride solution; a white precipitate of barium sulfate (BaSO₄) forms", examQ:{q:"Describe the test for sulfate ions and write the ionic equation for the reaction. [3 marks]", marks:3, ms:"Add dilute HCl then barium chloride solution (1); white precipitate forms (1); Ba²⁺ + SO₄²⁻ → BaSO₄ (1)"}},
      { id:"c13-008", tier:"triple_H", q:"How is infrared spectroscopy used to identify organic compounds?", a:"Infrared radiation is absorbed by bonds in molecules at specific frequencies; different functional groups absorb at characteristic wavenumbers, allowing identification by comparing to reference spectra", examQ:{q:"Explain how infrared spectroscopy can identify the presence of an -OH group in an organic molecule. [3 marks]", marks:3, ms:"IR radiation absorbed by O-H bond (1); at characteristic wavenumber around 2500-3300 cm⁻¹ (1); broad absorption peak in this region indicates -OH group present (1)"}},
    ]
  },

  c14: {
    name: "The Rate of Reaction & Equilibrium (Triple)",
    cards: [
      { id:"c14-001", tier:"triple_F", q:"What is the Maxwell-Boltzmann distribution?", a:"A graph showing the distribution of energies among molecules in a gas or liquid; shows that most molecules have intermediate energies, with few having very low or very high energies", examQ:{q:"Sketch and label a Maxwell-Boltzmann distribution and mark the activation energy. [3 marks]", marks:3, ms:"Curve starting at origin, rising to peak then falling asymptotically (1); x-axis: energy, y-axis: number of molecules (1); activation energy marked on x-axis to right of peak (1)"}},
      { id:"c14-002", tier:"triple_F", q:"How does increasing temperature affect the Maxwell-Boltzmann distribution?", a:"The peak shifts to the right and becomes lower/flatter; more molecules have energy greater than the activation energy, so the rate increases", examQ:{q:"Using the Maxwell-Boltzmann distribution, explain why increasing temperature increases the rate of reaction. [4 marks]", marks:4, ms:"Distribution shifts to higher energies/peak moves right (1); more molecules have energy ≥ activation energy (1); more frequent successful collisions (1); rate increases (1)"}},
      { id:"c14-003", tier:"triple_F", q:"How does a catalyst affect the activation energy and Maxwell-Boltzmann distribution?", a:"A catalyst provides an alternative reaction pathway with a lower activation energy; on the Maxwell-Boltzmann distribution, the activation energy line moves left, so more molecules can react", examQ:{q:"Explain how a catalyst increases the rate of reaction using the Maxwell-Boltzmann distribution. [4 marks]", marks:4, ms:"Catalyst provides alternative pathway with lower activation energy (1); activation energy line shifts left on distribution (1); greater proportion of molecules have sufficient energy (1); more successful collisions per unit time (1)"}},
      { id:"c14-004", tier:"triple_F", q:"What is Le Chatelier's principle?", a:"If a system at equilibrium is disturbed, the equilibrium shifts in the direction that opposes/counteracts the change", examQ:{q:"State Le Chatelier's principle and apply it to explain the effect of increasing pressure on a gaseous equilibrium where there are more moles of gas on the left. [4 marks]", marks:4, ms:"If equilibrium disturbed, system shifts to oppose change (1); increasing pressure favours side with fewer moles of gas (1); equilibrium shifts to right (1); to reduce pressure by decreasing number of gas molecules (1)"}},
      { id:"c14-005", tier:"triple_H", q:"How does changing concentration affect a dynamic equilibrium?", a:"Increasing the concentration of reactants shifts equilibrium to the right (more products formed); increasing product concentration shifts equilibrium to the left; the equilibrium constant (Kc) is unchanged by concentration changes", examQ:{q:"Explain the effect of increasing the concentration of a reactant on a system at equilibrium. [3 marks]", marks:3, ms:"Equilibrium shifts to right/towards products (1); to reduce the increased concentration of reactant (1); more products formed until new equilibrium established (1)"}},
      { id:"c14-006", tier:"triple_H", q:"What is the equilibrium constant Kc?", a:"Kc is the ratio of product concentrations to reactant concentrations at equilibrium, each raised to the power of their stoichiometric coefficients; Kc only changes with temperature", examQ:{q:"Write the expression for Kc for the reaction: N₂ + 3H₂ ⇌ 2NH₃ [2 marks]", marks:2, ms:"Kc = [NH₃]² / [N₂][H₂]³ (2); correct format with square brackets (1)"}},
      { id:"c14-007", tier:"triple_H", q:"How does temperature affect Kc?", a:"For an exothermic reaction, increasing temperature decreases Kc (equilibrium shifts left, less product); for an endothermic reaction, increasing temperature increases Kc (equilibrium shifts right, more product)", examQ:{q:"The forward reaction N₂ + 3H₂ ⇌ 2NH₃ is exothermic. Explain what happens to Kc when temperature is increased. [3 marks]", marks:3, ms:"Equilibrium shifts to left (endothermic direction) (1); to oppose the temperature increase (1); Kc decreases as less product at equilibrium (1)"}},
    ]
  },

  c15: {
    name: "Electrochemistry (Triple)",
    cards: [
      { id:"c15-001", tier:"triple_F", q:"What is a fuel cell?", a:"A device that generates electricity from the reaction of hydrogen and oxygen (or other fuels) without combustion; produces water as the only product when hydrogen is used", examQ:{q:"Describe how a hydrogen fuel cell generates electricity. [4 marks]", marks:4, ms:"Hydrogen oxidised at anode: H₂ → 2H⁺ + 2e⁻ (1); electrons flow through external circuit (1); oxygen reduced at cathode: O₂ + 4H⁺ + 4e⁻ → 2H₂O (1); water produced as only product (1)"}},
      { id:"c15-002", tier:"triple_F", q:"What are the advantages and disadvantages of hydrogen fuel cells?", a:"Advantages: only water produced, more efficient than combustion, quiet; Disadvantages: hydrogen is explosive, difficult to store and transport, currently produced from fossil fuels", examQ:{q:"Evaluate the use of hydrogen fuel cells as a replacement for petrol engines in cars. [5 marks]", marks:5, ms:"Advantage: only water produced, no CO₂ emissions (1); more efficient than combustion engine (1); Disadvantage: hydrogen explosive/difficult to store safely (1); infrastructure for hydrogen not widely available (1); hydrogen currently mainly produced from fossil fuels (1)"}},
      { id:"c15-003", tier:"triple_F", q:"What is the electrolysis of brine and what are its products?", a:"Brine (NaCl solution) is electrolysed to produce chlorine gas at the anode, hydrogen gas at the cathode, and sodium hydroxide solution remains", examQ:{q:"State the products of the electrolysis of brine and give one use of each. [4 marks]", marks:4, ms:"Chlorine at anode: used to make bleach/PVC (1); hydrogen at cathode: used in fuel cells/margarine production (1); sodium hydroxide in solution: used to make soap/bleach (1); any 4 correct points (1)"}},
      { id:"c15-004", tier:"triple_H", q:"How does the half-equation approach work in electrolysis?", a:"At cathode (reduction): positive ions gain electrons; at anode (oxidation): negative ions lose electrons; half-equations show electron transfer for each electrode separately", examQ:{q:"Write the half-equations for the electrolysis of brine. [4 marks]", marks:4, ms:"Cathode: 2H⁺ + 2e⁻ → H₂ (1); correct state/balancing (1); Anode: 2Cl⁻ → Cl₂ + 2e⁻ (1); correct state/balancing (1)"}},
      { id:"c15-005", tier:"triple_H", q:"Why is hydrogen produced at the cathode rather than sodium during electrolysis of brine?", a:"H⁺ ions are more easily reduced than Na⁺ ions; H⁺ ions have a less negative electrode potential, so they are preferentially discharged at the cathode", examQ:{q:"Explain why hydrogen gas is produced at the cathode during electrolysis of brine rather than sodium metal. [3 marks]", marks:3, ms:"Both H⁺ and Na⁺ present in solution (1); H⁺ is more easily reduced than Na⁺ (1); H⁺ preferentially discharged at cathode (1)"}},
    ]
  },

  c16: {
    name: "Transition Metals & Complex Ions (Triple)",
    cards: [
      { id:"c16-001", tier:"triple_F", q:"What are the properties of transition metals?", a:"High melting points, high densities, form coloured compounds, can act as catalysts, form complex ions, have variable oxidation states", examQ:{q:"State four properties of transition metals that distinguish them from Group 1 metals. [4 marks]", marks:4, ms:"Higher melting points (1); form coloured compounds (1); variable oxidation states (1); can act as catalysts / form complex ions (1)"}},
      { id:"c16-002", tier:"triple_F", q:"Why do transition metals have variable oxidation states?", a:"The 3d and 4s electrons are close in energy, so different numbers of electrons can be lost; this allows multiple stable oxidation states", examQ:{q:"Explain why iron can exist in both +2 and +3 oxidation states. [2 marks]", marks:2, ms:"3d and 4s orbitals are close in energy (1); different numbers of electrons can be removed to form stable ions (1)"}},
      { id:"c16-003", tier:"triple_F", q:"What is a complex ion?", a:"A central metal ion surrounded by ligands (molecules or ions that donate a lone pair of electrons to the metal), forming coordinate/dative covalent bonds", examQ:{q:"Explain what is meant by a complex ion, using [Cu(H₂O)₆]²⁺ as an example. [3 marks]", marks:3, ms:"Central metal ion (Cu²⁺) (1); surrounded by ligands (H₂O) (1); ligands donate lone pair to metal forming coordinate/dative bonds (1)"}},
      { id:"c16-004", tier:"triple_F", q:"What causes the colour of transition metal compounds?", a:"Electrons in the d orbitals are split into different energy levels by ligands; electrons absorb specific wavelengths of visible light when they jump between energy levels, and the complementary colour is seen", examQ:{q:"Explain why copper sulfate solution is blue. [4 marks]", marks:4, ms:"Cu²⁺ has electrons in d orbitals split by water ligands (1); electrons absorb red light when moving between d orbital energy levels (1); complementary colour (blue) is transmitted/seen (1); colour depends on metal ion and ligands present (1)"}},
      { id:"c16-005", tier:"triple_H", q:"What happens when NaOH is added to solutions of transition metal ions?", a:"Fe²⁺: green precipitate Fe(OH)₂; Fe³⁺: brown precipitate Fe(OH)₃; Cu²⁺: blue precipitate Cu(OH)₂; these are insoluble hydroxides formed by precipitation", examQ:{q:"Describe the results of adding excess sodium hydroxide solution to separate solutions of Fe²⁺ and Cu²⁺ ions. [4 marks]", marks:4, ms:"Fe²⁺: green precipitate of Fe(OH)₂ (1); does not dissolve in excess NaOH (1); Cu²⁺: blue precipitate of Cu(OH)₂ (1); does not dissolve in excess NaOH (1)"}},
    ]
  },

  c17: {
    name: "Atmospheric Chemistry (Triple)",
    cards: [
      { id:"c17-001", tier:"triple_F", q:"How has the Earth's atmosphere changed over time?", a:"Early atmosphere: mainly CO₂, H₂O vapour, little oxygen; over billions of years, photosynthesis by plants increased O₂ and decreased CO₂; nitrogen built up from volcanic activity and denitrification", examQ:{q:"Describe how the Earth's atmosphere has changed from its early formation to the present day. [5 marks]", marks:5, ms:"Early atmosphere rich in CO₂ and water vapour from volcanic activity (1); water condensed to form oceans (1); CO₂ dissolved in oceans (1); photosynthesis by early organisms produced oxygen (1); oxygen increased, CO₂ decreased, nitrogen built up over time (1)"}},
      { id:"c17-002", tier:"triple_F", q:"What are the main greenhouse gases and their sources?", a:"CO₂ (combustion, deforestation, respiration); CH₄ methane (livestock, rice paddies, landfill, natural gas); N₂O (agriculture, fertilisers); H₂O vapour (evaporation)", examQ:{q:"State three main greenhouse gases and one human activity that produces each. [3 marks]", marks:3, ms:"CO₂: combustion of fossil fuels (1); CH₄: livestock farming/landfill sites (1); N₂O: use of nitrogen fertilisers (1)"}},
      { id:"c17-003", tier:"triple_F", q:"How do greenhouse gases cause global warming?", a:"Greenhouse gases absorb infrared radiation emitted by Earth's surface, then re-emit it in all directions including back to Earth, trapping heat and raising temperature", examQ:{q:"Explain the greenhouse effect and how increasing greenhouse gas concentrations leads to global warming. [5 marks]", marks:5, ms:"Short wavelength solar radiation passes through atmosphere (1); Earth's surface absorbs and re-emits as infrared/long wavelength radiation (1); greenhouse gases absorb infrared radiation (1); re-emit in all directions including back to Earth (1); increased concentration traps more heat, raising global temperature (1)"}},
      { id:"c17-004", tier:"triple_F", q:"What are the consequences of climate change?", a:"Rising sea levels, more extreme weather events, loss of biodiversity, changes to agriculture, melting polar ice caps, ocean acidification", examQ:{q:"Describe four consequences of global climate change. [4 marks]", marks:4, ms:"Any four from: rising sea levels (1); more extreme weather/storms (1); loss of habitats/biodiversity (1); changes to crop growing regions (1); melting glaciers/ice caps (1); ocean acidification (1)"}},
      { id:"c17-005", tier:"triple_H", q:"What is carbon capture and storage (CCS)?", a:"A technology that captures CO₂ from power stations and industrial processes before it enters the atmosphere, compresses it and stores it underground in geological formations", examQ:{q:"Evaluate carbon capture and storage as a method of reducing global warming. [4 marks]", marks:4, ms:"Captures CO₂ before released to atmosphere (1); reduces greenhouse gas emissions from fossil fuel use (1); allows continued use of fossil fuels during energy transition (1); expensive technology, risk of CO₂ leaking, not widely deployed yet (1)"}},
      { id:"c17-006", tier:"triple_F", q:"How does acid rain form and what are its effects?", a:"SO₂ and NOₓ from burning fossil fuels dissolve in rainwater forming sulfuric and nitric acids; effects include damage to trees, buildings (especially limestone), lakes becoming acidic killing aquatic life", examQ:{q:"Explain how acid rain forms and describe two of its effects on the environment. [5 marks]", marks:5, ms:"SO₂/NOₓ released from burning fossil fuels (1); dissolve in rainwater to form sulfuric/nitric acid (1); effect 1: damages/kills trees by leaching minerals from soil (1); effect 2: lakes become acidic killing fish and aquatic organisms (1); damages limestone buildings/statues (1)"}},
      { id:"c17-007", tier:"triple_H", q:"What is the role of ozone in the atmosphere and how is it damaged?", a:"Ozone (O₃) in the stratosphere absorbs harmful UV radiation from the Sun; CFCs (chlorofluorocarbons) release Cl atoms that catalytically destroy ozone, creating the 'ozone hole'", examQ:{q:"Explain how CFCs damage the ozone layer. [4 marks]", marks:4, ms:"CFCs release chlorine radicals in stratosphere under UV light (1); Cl + O₃ → ClO + O₂ (1); ClO + O → Cl + O₂ (1); Cl is regenerated and acts as catalyst destroying many ozone molecules (1)"}},
    ]
  }
};

let total = 0;
Object.entries(TRIPLE_CHEMISTRY).forEach(([topic, data]) => {
  console.log(`${topic} (${data.name}): ${data.cards.length} cards`);
  total += data.cards.length;
});
console.log(`Total Triple Chemistry cards: ${total}`);

const TRIPLE_PHYSICS = {

  p8: {
    name: "Space Physics (Triple)",
    cards: [
      { id:"p8-001", tier:"triple_F", q:"What is the life cycle of a star like our Sun?", a:"Nebula → protostar → main sequence star → red giant → white dwarf → black dwarf", examQ:{q:"Describe the life cycle of a star similar in mass to our Sun. [5 marks]", marks:5, ms:"Nebula of gas and dust (1); gravitational collapse forms protostar (1); nuclear fusion of hydrogen on main sequence (1); red giant as hydrogen runs out (1); outer layers shed forming planetary nebula, core becomes white dwarf then black dwarf (1)"}},
      { id:"p8-002", tier:"triple_F", q:"What is the life cycle of a massive star?", a:"Nebula → protostar → main sequence → red supergiant → supernova → neutron star or black hole", examQ:{q:"Explain how a massive star ends its life differently from a star like our Sun. [4 marks]", marks:4, ms:"Massive star becomes red supergiant (1); undergoes supernova explosion (1); if remnant mass large enough forms black hole (1); otherwise forms neutron star (1)"}},
      { id:"p8-003", tier:"triple_F", q:"What is the Hertzsprung-Russell (HR) diagram?", a:"A graph plotting luminosity (y-axis) against surface temperature (x-axis) for stars; most stars lie on the main sequence; red giants and white dwarfs are in other regions", examQ:{q:"Describe the main features of a Hertzsprung-Russell diagram. [4 marks]", marks:4, ms:"Luminosity on y-axis, temperature on x-axis (1); temperature increases right to left (1); main sequence runs diagonally from top-left to bottom-right (1); red giants top-right, white dwarfs bottom-left (1)"}},
      { id:"p8-004", tier:"triple_F", q:"What is red-shift and what does it tell us about the universe?", a:"Red-shift is the increase in wavelength of light from distant galaxies; it shows galaxies are moving away from us, and the further away a galaxy, the greater its red-shift (Hubble's law)", examQ:{q:"Explain how red-shift provides evidence for the Big Bang theory. [4 marks]", marks:4, ms:"Light from distant galaxies is red-shifted (1); shows galaxies are moving away from us (1); further galaxies have greater red-shift so moving faster (1); suggests universe is expanding from a single point (Big Bang) (1)"}},
      { id:"p8-005", tier:"triple_F", q:"What is the Big Bang theory?", a:"The universe began from a very hot, dense single point approximately 13.8 billion years ago; it has been expanding ever since; evidence includes red-shift and cosmic microwave background radiation", examQ:{q:"State two pieces of evidence that support the Big Bang theory. [2 marks]", marks:2, ms:"Red-shift of distant galaxies showing universe is expanding (1); cosmic microwave background radiation (CMB) - thermal radiation left over from early universe (1)"}},
      { id:"p8-006", tier:"triple_H", q:"What is cosmic microwave background radiation (CMBR)?", a:"Low-level microwave radiation that fills the universe in all directions; it is the remnant thermal radiation from the early hot universe, predicted by the Big Bang theory and detected in 1965", examQ:{q:"Explain what cosmic microwave background radiation is and how it supports the Big Bang theory. [4 marks]", marks:4, ms:"Low energy microwave radiation detected uniformly from all directions in space (1); remnant of radiation from early hot dense universe (1); predicted by Big Bang theory (1); its detection in 1965 provided strong evidence for Big Bang (1)"}},
      { id:"p8-007", tier:"triple_F", q:"What forces act on a star during its main sequence lifetime?", a:"Gravitational force pulling inward (collapse) is balanced by radiation pressure from nuclear fusion pushing outward; this equilibrium maintains the star's size", examQ:{q:"Explain why a main sequence star remains stable in size. [3 marks]", marks:3, ms:"Gravitational force pulls matter inward (1); radiation pressure from nuclear fusion pushes outward (1); these forces balance so star remains stable (1)"}},
      { id:"p8-008", tier:"triple_H", q:"How does Hubble's law relate to the age of the universe?", a:"Hubble's law states that recession speed = Hubble constant × distance; by calculating how long galaxies have been moving apart, we can estimate the age of the universe (~13.8 billion years)", examQ:{q:"Explain how Hubble's constant can be used to estimate the age of the universe. [3 marks]", marks:3, ms:"Hubble's law: v = H₀d (1); age ≈ 1/H₀ (1); gives estimate of ~13.8 billion years for age of universe (1)"}},
    ]
  },

  p9: {
    name: "Electromagnets & Motors (Triple)",
    cards: [
      { id:"p9-001", tier:"triple_F", q:"What is the motor effect?", a:"When a current-carrying conductor is placed in a magnetic field, it experiences a force; the direction is given by Fleming's left-hand rule", examQ:{q:"Describe the motor effect and state the factors that affect the size of the force. [4 marks]", marks:4, ms:"Current-carrying conductor in magnetic field experiences force (1); force is perpendicular to both current and field (1); force increases with greater current (1); force increases with stronger magnetic field (1)"}},
      { id:"p9-002", tier:"triple_F", q:"What is Fleming's left-hand rule?", a:"For a motor (current in a magnetic field): point left hand with First finger in direction of Field, seCond finger in direction of Current, thuMb points in direction of Motion (force)", examQ:{q:"Describe how Fleming's left-hand rule is used to find the direction of force on a current-carrying conductor. [3 marks]", marks:3, ms:"First finger points in direction of magnetic field (1); second finger points in direction of conventional current (1); thumb points in direction of force/motion (1)"}},
      { id:"p9-003", tier:"triple_F", q:"How does a simple DC motor work?", a:"A coil of wire carrying current in a magnetic field experiences forces on opposite sides in opposite directions, causing rotation; a split-ring commutator reverses current every half turn to maintain rotation in the same direction", examQ:{q:"Explain how a split-ring commutator allows a DC motor to rotate continuously. [4 marks]", marks:4, ms:"Current-carrying coil in magnetic field experiences force (1); opposite sides of coil experience forces in opposite directions causing rotation (1); after half turn coil would slow and reverse without commutator (1); commutator reverses current every half turn maintaining rotation in same direction (1)"}},
      { id:"p9-004", tier:"triple_F", q:"What is electromagnetic induction?", a:"When a conductor moves through a magnetic field (or a magnetic field changes through a conductor), an EMF is induced; if the circuit is complete, a current flows", examQ:{q:"State the conditions needed for electromagnetic induction to occur. [3 marks]", marks:3, ms:"Conductor must move relative to magnetic field (1); or magnetic field must change/move relative to conductor (1); rate of change of flux linkage determines size of induced EMF (1)"}},
      { id:"p9-005", tier:"triple_F", q:"What is Faraday's law?", a:"The magnitude of the induced EMF is proportional to the rate of change of magnetic flux linkage", examQ:{q:"State Faraday's law and explain two ways to increase the induced EMF in a coil. [4 marks]", marks:4, ms:"Induced EMF proportional to rate of change of flux linkage (1); increase speed of movement (1); use stronger magnet/increase field strength (1); increase number of turns on coil (1)"}},
      { id:"p9-006", tier:"triple_F", q:"What is Lenz's law?", a:"The induced current always flows in a direction to oppose the change that caused it (conservation of energy)", examQ:{q:"Explain Lenz's law and how it is consistent with conservation of energy. [3 marks]", marks:3, ms:"Induced current opposes the change causing it (1); if it aided the change, energy would be created from nothing (1); work must be done against the opposing force to maintain motion (1)"}},
      { id:"p9-007", tier:"triple_F", q:"How does a transformer work?", a:"An alternating current in the primary coil creates a changing magnetic field in the iron core; this induces an alternating EMF in the secondary coil; the voltage ratio equals the turns ratio", examQ:{q:"Explain how a step-up transformer increases voltage. [4 marks]", marks:4, ms:"AC in primary coil creates changing magnetic field in iron core (1); changing field induces EMF in secondary coil (1); secondary coil has more turns than primary (1); voltage increased in proportion to turns ratio (1)"}},
      { id:"p9-008", tier:"triple_H", q:"Why must transformers use AC not DC?", a:"Transformers require a constantly changing magnetic field to induce an EMF; DC produces a constant magnetic field which only induces an EMF at switch-on and switch-off", examQ:{q:"Explain why transformers only work with alternating current. [3 marks]", marks:3, ms:"Transformer needs changing magnetic flux to induce EMF (1); AC produces constantly changing current and magnetic field (1); DC produces constant field so no EMF induced (except at switch on/off) (1)"}},
    ]
  },

  p10: {
    name: "Particle Physics (Triple)",
    cards: [
      { id:"p10-001", tier:"triple_F", q:"What are the fundamental particles in the standard model?", a:"Quarks (make up hadrons like protons and neutrons), leptons (e.g. electrons, neutrinos), and bosons (force-carrying particles e.g. photons)", examQ:{q:"State the three categories of fundamental particles in the standard model. [3 marks]", marks:3, ms:"Quarks (1); leptons (1); bosons/force carriers (1)"}},
      { id:"p10-002", tier:"triple_F", q:"What quarks make up a proton and a neutron?", a:"Proton: 2 up quarks + 1 down quark (uud); Neutron: 1 up quark + 2 down quarks (udd)", examQ:{q:"State the quark composition of a proton and a neutron. [2 marks]", marks:2, ms:"Proton: uud (two up, one down) (1); Neutron: udd (one up, two down) (1)"}},
      { id:"p10-003", tier:"triple_F", q:"What is beta-minus decay in terms of quarks?", a:"A down quark changes into an up quark, converting a neutron into a proton; an electron and antineutrino are emitted", examQ:{q:"Describe beta-minus decay in terms of quarks. [3 marks]", marks:3, ms:"Down quark changes to up quark (1); neutron becomes proton (1); electron and electron antineutrino emitted (1)"}},
      { id:"p10-004", tier:"triple_F", q:"What is antimatter?", a:"For every particle there is a corresponding antiparticle with the same mass but opposite charge; when a particle meets its antiparticle, they annihilate and produce energy (photons)", examQ:{q:"Explain what happens when a particle meets its antiparticle. [3 marks]", marks:3, ms:"Particle and antiparticle annihilate (1); mass converted to energy (1); two gamma ray photons produced (1)"}},
      { id:"p10-005", tier:"triple_H", q:"What is pair production?", a:"A high-energy photon (gamma ray) spontaneously converts into a particle-antiparticle pair (e.g. electron and positron); energy must be sufficient for the mass of both particles (E=mc²)", examQ:{q:"Explain the conditions needed for pair production to occur. [3 marks]", marks:3, ms:"High energy gamma ray photon required (1); photon energy must equal or exceed combined mass-energy of particle pair (E=mc²) (1); produces particle and its antiparticle e.g. electron and positron (1)"}},
    ]
  },

  p11: {
    name: "Medical Physics (Triple)",
    cards: [
      { id:"p11-001", tier:"triple_F", q:"How do X-rays form images of the body?", a:"X-rays are absorbed by dense materials (bone) and transmitted through soft tissue; a photographic plate or detector records the pattern, producing a shadow image", examQ:{q:"Explain how X-rays are used to image bones in the body. [4 marks]", marks:4, ms:"X-rays directed through the body (1); dense materials e.g. bone absorb X-rays (1); soft tissue transmits X-rays (1); detector records pattern, bones appear white/lighter (1)"}},
      { id:"p11-002", tier:"triple_F", q:"What is a CT scan and how does it differ from a conventional X-ray?", a:"CT (computed tomography) uses X-rays taken from many angles around the body; computer reconstructs a 3D image; provides more detail than a flat X-ray", examQ:{q:"Compare CT scanning with conventional X-ray imaging. [4 marks]", marks:4, ms:"CT uses X-rays from multiple angles (1); computer reconstructs 3D cross-sectional images (1); conventional X-ray produces 2D shadow image (1); CT provides greater detail but higher radiation dose (1)"}},
      { id:"p11-003", tier:"triple_F", q:"How does ultrasound imaging work?", a:"High frequency sound waves are transmitted into the body; they reflect off boundaries between tissues; the reflected waves are detected and used to build an image based on echo timing", examQ:{q:"Explain how ultrasound can be used to produce an image of a foetus. [5 marks]", marks:5, ms:"Ultrasound transducer emits high frequency sound pulses (1); sound travels through tissues (1); reflects at boundaries between different tissues (1); reflected pulses detected by transducer (1); computer calculates distances from timing and builds image (1)"}},
      { id:"p11-004", tier:"triple_F", q:"What are the advantages of ultrasound over X-rays for imaging?", a:"Ultrasound is non-ionising so safe for pregnant women and repeated use; can image soft tissue; real-time imaging possible; X-rays cannot easily image soft tissue and carry radiation risk", examQ:{q:"Explain why ultrasound is preferred over X-rays for imaging a developing foetus. [3 marks]", marks:3, ms:"Ultrasound is non-ionising/does not damage DNA (1); safe for mother and foetus (1); can image soft tissue/moving structures in real time (1)"}},
      { id:"p11-005", tier:"triple_H", q:"What is MRI and how does it work?", a:"Magnetic Resonance Imaging uses strong magnetic fields and radio waves to align and then disturb hydrogen nuclei in the body; as they realign they emit radio waves which are detected to build an image", examQ:{q:"Describe the principles of MRI scanning. [4 marks]", marks:4, ms:"Strong magnetic field aligns hydrogen nuclei in body (1); radio waves applied, nuclei absorb energy and become misaligned (1); when radio waves turned off, nuclei realign emitting radio waves (1); computer analyses emitted signals to construct detailed image (1)"}},
      { id:"p11-006", tier:"triple_F", q:"What is radiation therapy and how is it used to treat cancer?", a:"High doses of ionising radiation (usually gamma rays or X-rays) are directed at a tumour from multiple angles; the radiation damages the DNA of cancer cells, preventing them from dividing", examQ:{q:"Explain how radiotherapy is used to treat cancer and why radiation is directed from multiple angles. [4 marks]", marks:4, ms:"Ionising radiation directed at tumour (1); damages DNA of cancer cells preventing division (1); directed from multiple angles so tumour receives high dose (1); surrounding healthy tissue receives lower dose from each beam (1)"}},
    ]
  },

  p12: {
    name: "Thermodynamics (Triple)",
    cards: [
      { id:"p12-001", tier:"triple_F", q:"What is specific heat capacity?", a:"The energy required to raise the temperature of 1 kg of a substance by 1°C (or 1K); Q = mcΔT", examQ:{q:"Define specific heat capacity and write the equation linking it to energy, mass and temperature change. [3 marks]", marks:3, ms:"Energy needed to raise temperature of 1kg by 1°C/K (1); Q = mcΔT (1); units: J/kg°C or J/kg/K (1)"}},
      { id:"p12-002", tier:"triple_F", q:"What is specific latent heat?", a:"The energy required to change the state of 1 kg of a substance without changing its temperature; Q = mL", examQ:{q:"Explain why temperature does not change during a change of state despite energy being supplied. [3 marks]", marks:3, ms:"Energy used to break/form intermolecular bonds (1); not used to increase kinetic energy of particles (1); temperature only changes when particle kinetic energy changes (1)"}},
      { id:"p12-003", tier:"triple_H", q:"What is the difference between specific latent heat of fusion and vaporisation?", a:"Latent heat of fusion: energy to melt/freeze 1kg (solid↔liquid); Latent heat of vaporisation: energy to boil/condense 1kg (liquid↔gas); vaporisation is much larger as bonds must be completely broken", examQ:{q:"Explain why the specific latent heat of vaporisation is much larger than the specific latent heat of fusion for the same substance. [3 marks]", marks:3, ms:"Fusion: partial breaking of intermolecular bonds (1); vaporisation: complete separation of molecules/all bonds broken (1); much more energy required to fully separate molecules (1)"}},
      { id:"p12-004", tier:"triple_F", q:"What is the gas pressure law (Gay-Lussac's Law)?", a:"For a fixed mass of gas at constant volume, pressure is proportional to absolute temperature: P/T = constant; P₁/T₁ = P₂/T₂", examQ:{q:"A gas has pressure 100 kPa at 300K. Calculate the pressure at 450K (volume constant). [3 marks]", marks:3, ms:"P₁/T₁ = P₂/T₂ (1); 100/300 = P₂/450 (1); P₂ = 150 kPa (1)"}},
      { id:"p12-005", tier:"triple_H", q:"What is the ideal gas equation?", a:"PV = nRT, where P = pressure (Pa), V = volume (m³), n = moles, R = gas constant (8.31 J/mol/K), T = temperature (K)", examQ:{q:"Calculate the pressure of 2 moles of an ideal gas at 300K in a volume of 0.05 m³. [3 marks]", marks:3, ms:"PV = nRT (1); P = 2 × 8.31 × 300 / 0.05 (1); P = 99,720 Pa ≈ 100 kPa (1)"}},
    ]
  },

  p13: {
    name: "Magnetic Fields & Electromagnetism (Triple)",
    cards: [
      { id:"p13-001", tier:"triple_F", q:"What is magnetic flux density (B) and what are its units?", a:"Magnetic flux density is the strength of a magnetic field; it is measured in Tesla (T); it represents the force per unit length per unit current on a conductor", examQ:{q:"Define magnetic flux density and state its unit. [2 marks]", marks:2, ms:"Strength of magnetic field / force per unit current per unit length on conductor (1); Tesla (T) (1)"}},
      { id:"p13-002", tier:"triple_F", q:"What is the equation for force on a current-carrying conductor?", a:"F = BIL, where F = force (N), B = magnetic flux density (T), I = current (A), L = length of conductor in field (m)", examQ:{q:"A 0.5m wire carrying 3A is placed perpendicular to a magnetic field of 0.2T. Calculate the force on the wire. [3 marks]", marks:3, ms:"F = BIL (1); F = 0.2 × 3 × 0.5 (1); F = 0.3 N (1)"}},
      { id:"p13-003", tier:"triple_F", q:"What is the Hall effect?", a:"When a current-carrying conductor is in a magnetic field, a voltage (Hall voltage) develops across the conductor perpendicular to both current and field, due to charge carriers being deflected", examQ:{q:"Explain the Hall effect. [4 marks]", marks:4, ms:"Current-carrying conductor in magnetic field (1); charge carriers deflected by magnetic force (1); build up of charge on one side creates electric field (1); Hall voltage develops perpendicular to current and field (1)"}},
      { id:"p13-004", tier:"triple_H", q:"What is magnetic flux and flux linkage?", a:"Magnetic flux (Φ) = BA (flux density × area); flux linkage = NΦ = NBA (for a coil of N turns); measured in Weber (Wb)", examQ:{q:"A coil of 200 turns has an area of 0.01m² in a field of 0.5T. Calculate the flux linkage. [3 marks]", marks:3, ms:"Flux linkage = NBA (1); = 200 × 0.5 × 0.01 (1); = 1 Wb (1)"}},
      { id:"p13-005", tier:"triple_H", q:"What is the equation for induced EMF?", a:"EMF = -N × ΔΦ/Δt (Faraday's law); the rate of change of flux linkage determines the induced EMF; the negative sign indicates Lenz's law (opposition)", examQ:{q:"The flux through a 100-turn coil changes from 0.02Wb to 0.08Wb in 0.5s. Calculate the induced EMF. [3 marks]", marks:3, ms:"EMF = N × ΔΦ/Δt (1); = 100 × (0.08-0.02)/0.5 (1); = 12 V (1)"}},
    ]
  },

  p14: {
    name: "Nuclear Physics (Triple)",
    cards: [
      { id:"p14-001", tier:"triple_F", q:"What is nuclear fission?", a:"The splitting of a large unstable nucleus (e.g. uranium-235) into two smaller nuclei when struck by a neutron; releases large amounts of energy and 2-3 neutrons which can cause further fissions (chain reaction)", examQ:{q:"Describe nuclear fission and explain how a chain reaction occurs. [5 marks]", marks:5, ms:"Large nucleus e.g. U-235 absorbs neutron (1); becomes unstable and splits into two smaller nuclei (1); releases large amount of energy (1); 2-3 neutrons released (1); these cause further fissions creating a chain reaction (1)"}},
      { id:"p14-002", tier:"triple_F", q:"What is nuclear fusion?", a:"The joining of two light nuclei (e.g. hydrogen isotopes) to form a heavier nucleus; releases even more energy per kilogram than fission; requires extremely high temperatures (millions of degrees)", examQ:{q:"Compare nuclear fusion and fission as energy sources. [5 marks]", marks:5, ms:"Fusion: light nuclei combine, fission: heavy nucleus splits (1); both release large amounts of energy (1); fusion releases more energy per kg (1); fusion uses hydrogen (abundant), fission uses uranium (limited) (1); fusion produces no radioactive waste, fission produces radioactive waste (1)"}},
      { id:"p14-003", tier:"triple_F", q:"What is binding energy?", a:"The energy required to completely separate all nucleons in a nucleus; or equivalently, the energy released when a nucleus forms from separate nucleons; related to mass defect by E=mc²", examQ:{q:"Explain what is meant by nuclear binding energy and how it relates to nuclear stability. [4 marks]", marks:4, ms:"Energy needed to separate all nucleons (1); or energy released when nucleus assembles from nucleons (1); greater binding energy per nucleon = more stable nucleus (1); iron-56 has highest binding energy per nucleon (most stable) (1)"}},
      { id:"p14-004", tier:"triple_H", q:"What is mass defect?", a:"The difference between the mass of separate nucleons and the actual mass of the nucleus; the 'missing' mass is converted to binding energy according to E=mc²", examQ:{q:"Explain what mass defect is and calculate the energy released when a nucleus forms with a mass defect of 5×10⁻²⁹ kg. [4 marks]", marks:4, ms:"Mass of nucleus less than mass of constituent nucleons (1); difference converted to energy (1); E = mc² (1); E = 5×10⁻²⁹ × (3×10⁸)² = 4.5×10⁻¹² J (1)"}},
      { id:"p14-005", tier:"triple_F", q:"What is the difference between nuclear fission reactors and fusion reactors?", a:"Fission reactors exist and generate electricity commercially (using uranium); fusion reactors are still experimental (e.g. ITER/JET) because maintaining the extreme temperatures and pressures needed for sustained fusion is technically very challenging", examQ:{q:"Explain why nuclear fusion has not yet been used as a commercial energy source. [4 marks]", marks:4, ms:"Requires extremely high temperatures millions of degrees (1); difficult to contain plasma at these temperatures (1); more energy currently needed to initiate fusion than is released (1); engineering challenges of sustained reaction not yet solved (1)"}},
      { id:"p14-006", tier:"triple_H", q:"How is the activity of a radioactive source related to the number of undecayed nuclei?", a:"Activity (A) = decay constant (λ) × number of undecayed nuclei (N); A = λN; decay constant is the probability of a nucleus decaying per unit time", examQ:{q:"A sample contains 5×10²⁰ atoms of a radioactive isotope with decay constant 2×10⁻⁴ s⁻¹. Calculate the activity. [3 marks]", marks:3, ms:"A = λN (1); A = 2×10⁻⁴ × 5×10²⁰ (1); A = 1×10¹⁷ Bq (1)"}},
    ]
  }
};

let total = 0;
Object.entries(TRIPLE_PHYSICS).forEach(([topic, data]) => {
  console.log(`${topic} (${data.name}): ${data.cards.length} cards`);
  total += data.cards.length;
});
console.log(`Total Triple Physics cards: ${total}`);
